vitrine/urls.py
from django.urls import path
from. import views

urlpatterns = [
    path("merci",views.merci_site, name='merci-url'),
    path("bmr",views.bmr_site, name='bmr-url'),
    path("",views.accueil_site, name='accueil-url'),
]

zeshortcut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('paulk/', admin.site.urls),
    path('', include("vitrine.urls")),
]

vitrine/models.py
from django.db import models

# Create your models here.

vitrine/forms.py
from django import forms

SEX_CHOICES = {
    "0": "Homme",
    "1": "Femme",
}
class BmrForm(forms.Form):
    sex = forms.ChoiceField(
        label='Quel est votre sex ?',
        widget=forms.RadioSelect,
        choices=SEX_CHOICES,
    )
    age = forms.CharField(
        max_length=32,
        label='Quel âge avez-vous ?',
        widget=forms.NumberInput(attrs={'placeholder':'Âge'})
    )
    weight = forms.CharField(
        label='Combien pesez-vous ?',
        widget=forms.NumberInput(attrs={'placeholder': 'Poids'})
    )
    size = forms.CharField(
        max_length=100,
        label='Combien mesurez-vous ?',
        widget=forms.NumberInput(attrs={'placeholder':'Taille'})
    )
    
    
TYPE_PLAN = {
    "0": "prendre_du_poids",
    "1": "perdre_du_poids",
}
class PlanForm(forms.Form):
    typePlan = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=TYPE_PLAN,
    )
    userMail = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
    )

vitrine/views.py
from django.shortcuts import render, redirect
from .forms import BmrForm, PlanForm
import requests
from django.http import JsonResponse
import json

def accueil_site(request):
    reqUrl = "http://localhost:3333/getkalperday"

    if request.method == 'POST':
        form = BmrForm(request.POST)
        
        if form.is_valid():
            sex = form.cleaned_data["sex"]
            age = form.cleaned_data["age"]
            weight = form.cleaned_data["weight"]
            size = form.cleaned_data["size"]
            
            
            headers = {
                'Content-Type': 'application/json'
            }
            
            payload = json.dumps({
                "sex": sex,
                "age": age,
                "weight": weight,
                "size": size,
            })

            response = requests.request("POST",reqUrl, headers=headers, data=payload)
            if response.status_code == 200:
                bmr_data = response.json()
                api_bmr = bmr_data.get('YourBMR', None)
                if api_bmr:
                    request.session['api_bmr'] = api_bmr
                    return redirect('bmr-url')
                else:
                    return JsonResponse({"message": "Erreur: Aucun BMR trouvé dans la réponse de l'API"})
            else :
                return JsonResponse({"message": f"Erreur: {response.status_code} - {response.text}"}, status=response.status_code)
    else:
        return render(request, "accueil.html")

def bmr_site(request):
    api_bmr = request.session.get('api_bmr')
    print(api_bmr)
    reqUrl = "http://localhost:3333/generate-meals"

    if request.method == 'POST':
        form = PlanForm(request.POST)
        
        if form.is_valid():
            typePlan = form.cleaned_data["typePlan"]
            userMail = form.cleaned_data["userMail"]
            
            
            headers = {
                'Content-Type': 'application/json'
            }
            
            payload = json.dumps({
                "BMR": api_bmr,
                "typePlan": typePlan,
                "userMail": userMail,
            })

            response = requests.request("POST", reqUrl, headers=headers, data=payload)
            print(response)
            return redirect('merci-url')
            
    else:
        context = {'api_bmr': api_bmr}
    return render(request, "bmr.html", context=context)

def merci_site(request):
    return render(request, "merci.html")

vitrine/templates/accueil.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
    </head>
    <body>
        <div class="body">
            <div class="entete">
                <a href="{% url 'accueil-url' %}"><img src="{% static "images/Capture_decran_2024-02-20_130616.png" %}" /></a>
            </div>
            {% comment %} ------------------------------------------- {% endcomment %}
            <form method="post">
                {% csrf_token %}
                <div class="question" style="display:block;">
                    <label for="id_sex" class="sex">Quel est votre genre ?</label>
                    <div id="id_sex" class="radio">
                        <div>
                            <label for="id_sex_0" class="radio0">
                                <input type="radio" name="sex" value="0" required id="id_sex_0">
                                <span>Homme</span>
                                <img src="{% static 'images/boy_svg.svg' %}" />
                            </label>
                        </div>
                        <div>
                            <label for="id_sex_1" class="radio0">
                                <input type="radio" name="sex" value="1" required id="id_sex_1">
                                <span>Femme</span>
                                <img src="{% static 'images/girl_svg.svg' %}" />
                            </label>
                        </div>
                    </div>
                </div>
                <div class="question">
                    <div class="div">
                        <label for="id_age">Quel âge avez-vous ?</label>
                        <div class="div0">
                            <input type="number" name="age" placeholder="Âge" maxlength="32" required id="id_age">
                            ans
                        </div>
                    </div>
                </div>
                <div class="question">
                    <div class="div">
                        <label for="id_weight" class="weight">Combien pesez-vous ?</label>
                        <div class="div0">
                            <input type="number" name="weight" placeholder="Poids" required id="id_weight">
                            kg
                        </div>
                    </div>
                </div>
                <div class="question">
                    <div class="div">
                        <label for="id_size" class="size">Combien mesurez-vous ?</label>
                        <div class="div0">
                            <input type="number" name="size" placeholder="Taille" maxlength="100" required id="id_size">
                            cm
                        </div>
                    </div>
                </div>
                <div class="question">
                    <div class="summary">
                        <h2>Résumé du formulaire :</h2>
                        <p>Genre : <span id="summary-sex"></span></p>
                        <p>Âge : <span id="summary-age"></span> ans</p>
                        <p>Poids : <span id="summary-weight"></span> kg</p>
                        <p>Taille : <span id="summary-size"></span> cm</p>
                    </div>
                    <input type="submit" value="Envoyer">
                </div>
            </form>
            <div class="next">
                <button>Suivant</button>
            </div>
        </div>
        {% comment %} ------------------------------------------- {% endcomment %}
        <div class="footer">
            <img src="{% static "images/footer_svg.svg" %}" />
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var questions = document.querySelectorAll('.question');
                var summarySex = document.getElementById('summary-sex');
                var summaryAge = document.getElementById('summary-age');
                var summaryWeight = document.getElementById('summary-weight');
                var summarySize = document.getElementById('summary-size');

                var currentQuestion = 0;

                var nextButton = document.querySelector('.next button');

                nextButton.addEventListener('click', function() {
                    if (currentQuestion === 0) {
                        var radioInputs = document.querySelectorAll('input[type="radio"][name="sex"]');
                        var selectedValue = null;
                        radioInputs.forEach(function(radioInput) {
                            if (radioInput.checked) {
                                selectedValue = radioInput.value;
                            }
                        });
                        console.log(selectedValue);
                        if (selectedValue == 0){
                            summarySex.textContent = 'Homme';
                        }
                        else {
                            summarySex.textContent = 'Femme';
                        }
                        console.log(summarySex.textContent);
                    } else if (currentQuestion === 1) {
                        summaryAge.textContent = document.getElementById('id_age').value;
                        console.log(document.getElementById('id_age').value)
                    } else if (currentQuestion === 2) {
                        summaryWeight.textContent = document.getElementById('id_weight').value;
                        console.log(document.getElementById('id_weight').value)
                    } else if (currentQuestion === 3) {
                        summarySize.textContent = document.getElementById('id_size').value;
                        console.log(document.getElementById('id_size').value)
                    }

                    questions[currentQuestion].style.display = 'none';

                    currentQuestion++;

                    if (currentQuestion < questions.length) {
                        questions[currentQuestion].style.display = 'block';
                    } else {
                        nextButton.style.display = 'none';
                    }
                    if (currentQuestion === questions.length - 1) {
                        nextButton.style.display = 'none';
                    }
                });
            });
        </script>
    </body>
</html>

vitrine/templates/bmr.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/bmr.css" %}">
    </head>
    <body>
        <div class="body">
            <div class="entete">
                <a href="{% url 'accueil-url' %}"><img src="{% static "images/Capture_decran_2024-02-20_130616.png" %}" /></a>
            </div>
            <h1>Votre total calorique est de : {{api_bmr}}</h1>
            <form method="post">
                {% csrf_token %}
                <div class="type_plan">
                    <div id="id_typePlan" class="radio">
                        <div class="radio0">
                            <label for="id_typePlan_0" class="radio0_0">
                                <input type="radio" name="typePlan" value="0" required id="id_typePlan_0" />
                                prendre de la masse
                                <img src="{% static "images/muscle.png" %}" />
                            </label>
                        </div>
                        <div class="radio0">
                            <label for="id_typePlan_1" class="radio0_0">
                                <input type="radio" name="typePlan" value="1" required id="id_typePlan_1" />
                                perdre du poids
                                <img src="{% static "images/pomme.png" %}" />
                            </label>
                        </div>
                    </div>
                </div>
                <div class="mail">
                    <label for="id_userMail">Mail :</label>
                    <input type="email" name="userMail" placeholder="Email" maxlength="100" required id="id_userMail">
                </div>
                <input type="submit" value="Submit" />
            </form>
        </div>
        <div class="footer">
            <img src="{% static "images/footer_svg.svg" %}" />
        </div>
    </body>
</html>

vitrine/templates/merci.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
    </head>
    <body>
        <div class="body">
            <div class="entete">
                <a href="{% url 'accueil-url' %}"><img src="{% static "images/Capture_decran_2024-02-20_130616.png" %}" /></a>
            </div>
            <h1>MERCI !!</h1>
            <p>Un mail vous à été envoyé, merci de votre fidélité.</p>
            <p>Noubliez pas de vérifier vos spams</p>
        </div>
        <div class="footer">
            <img src="{% static "images/footer_svg.svg" %}" />
        </div>
    </body>
</html>